# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [29]:
#code here

# Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

import numpy as np

arr = np.arange(12)
print("\n 1D \n",arr)
arr = arr.reshape(3, 4)
print("\n Reshaped \n",arr)



 1D 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:

import numpy as np

# Concatenate two NumPy arrays horizontally
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Horizontal concatenation:")
print(np.concatenate((arr1, arr2), axis=1))

# Concatenate two NumPy arrays vertically
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])
print("\nVertical concatenation:")
print(np.concatenate((arr3, arr4), axis=0))


Horizontal concatenation:
[[1 2 5 6]
 [3 4 7 8]]

Vertical concatenation:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [36]:
#code here

def classify_emails(emails):
  important_emails = []
  promotions_emails = []
  spam_emails = []

  for email in emails:
    if "urgent" in email or "important" in email:
      important_emails.append(email)
    elif "sale" in email or "discount" in email:
      promotions_emails.append(email)
    else:
      spam_emails.append(email)

  return important_emails, promotions_emails, spam_emails

emails = ["Important meeting tomorrow", "50% off sale on shoes", "Nigerian prince needs your help"]

lower = [x.lower() for x in emails]

important, promotions, spam = classify_emails(lower)

print("Important emails:", important)
print("Promotions emails:", promotions)
print("Spam emails:", spam)


Important emails: ['important meeting tomorrow']
Promotions emails: ['50% off sale on shoes']
Spam emails: ['nigerian prince needs your help']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [37]:
#code here

dictionary = {
    "hello": "hola",
    "goodbye": "adiós",
    "thank you": "gracias",
    "you're welcome": "de nada",
    "yes": "sí",
    "no": "no",
    "please": "por favor",

}

while True:
  word = input("Enter an English word (or 'exit' to quit): ")
  if word == "exit":
    break

  if word in dictionary:
    print(f"Translation: {dictionary[word]}")
  else:
    print(f"Translation not available for '{word}'")


Enter an English word (or 'exit' to quit): you're welcome
Translation: de nada
Enter an English word (or 'exit' to quit): exit


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [38]:
import pandas as pd

url = 'https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv'
df = pd.read_csv(url)

# Calculate the total global sales
total_sales = df['Global_Sales'].sum()
print(f"Total global sales: {total_sales}")


Total global sales: 8920.44


In [42]:
# Find the game with the highest global sales.
df.loc[df['Global_Sales'] == df['Global_Sales'].max(), 'Name']

0    Wii Sports
Name: Name, dtype: object

In [43]:
# Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
df.agg(
    {
        "NA_Sales": "mean",
        "EU_Sales": "mean",
        "JP_Sales": "mean",
        "Other_Sales": "mean"

    }
)

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [44]:
# Find the top 5 most popular game genres based on global sales.
df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).head(5)


Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [45]:
# Group by genre and region
sales_by_genre_and_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()

# most popular genre in North America (NA_Sales)
most_popular_genre_na = sales_by_genre_and_region['NA_Sales'].idxmax()

# total sales for each genre in each region
print("Total Sales by Genre and Region:")
print(sales_by_genre_and_region)

print("\nMost popular genre in North America (NA_Sales):", most_popular_genre_na)

Total Sales by Genre and Region:
              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

Most popular genre in North America (NA_Sales): Action


In [46]:
df.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [47]:
df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)


Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [48]:
df_market_share = df.groupby('Genre')['Global_Sales'].sum() / df['Global_Sales'].sum() * 100
print(df_market_share)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [49]:
df['NA_Sales'].corr(df['EU_Sales'])

0.7677267483702631

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
